config/routes.rb
WhosDown::Application.routes.draw do

root :to => 'pages#home'
get 'about' => 'pages#about'
get 'signup' =>'pages#signup'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  
  def action
  end
  
  def signup
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
<small>
<p>By </><A HREF="http://aaronwilson.me" target="_blank">Aaron
Wilson</A> and </><A HREF="http://www.linkedin.com/pub/joseph-schaffer/51/7/b70" target="_blank">Joe Schaffer</A>
<br>
</small>
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
 
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
 
      <!-- Be sure to leave the brand out there if you want it shown -->
      <a class="brand" href="#">Who's Down</a>
 
      <!-- Everything you want hidden at 940px or less, place within here -->
      <div class="nav-collapse collapse">
      <center> <div class="header">
<ul class="nav">
<li><%= link_to "Home", root_path %></li>
<li><%= link_to "About", about_path %></li>
</ul>

<ul class="nav pull-right">
<li><%= link_to "Signup", signup_path %></li>
</ul>
</div>
        <!-- .nav, .navbar-search, .navbar-form, etc -->
      </div>
 
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Who's Down</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>
<div class="container">
<%= yield %>

<%= render 'layouts/footer' %>

</body>
</html>

app/views/pages/about.html.erb
<center> <h1>About</h1>
<p>
We're not quite ready to say what Who's Down is yet but we think you'll really like it when you see it.
</p>

app/views/pages/home.html.erb
<link rel="stylesheet" href="homepage.css.scss">

<center> 

<div class="herotext">
<H1>Who's Down is coming soonish.</H1>
</div>

<br>

<div class="img">
<img src="https://lh6.googleusercontent.com/-YTSeRA0ljYw/UZ6yydUCi1I/AAAAAAAACLU/tZAbezIVWnU/s398-no/icon.png" />
</div>

<br>

app/views/pages/signup.html.erb
<center> <h1>Hop on</h1>
<p>
We're just getting started but you're welcome to join early if you like bugs.
</p>